import 'iconify-icon'
import './components/App'
import './components/EditPanel'
import './components/Sanji Logo'
import './components/TipsDialog'
import './components/WantedButton'
import './components/WantedPoster'
import './style.css'
